# Jekyll Configuration for Oriol Colomé Font - Music Tech Generalist

# Site settings
title: "Oriol Colomé Font"
description: "Music-Tech Generalist: All Things Music. Growth Lead & Product Owner at My Sheet Music Transcriptions. Bridging the gap between artistic vision and technical implementation."
email: "oriolcolomefont@gmail.com"
url: "https://oriolcolomefont.github.io"
baseurl: ""

# Author information
author:
  name: "Oriol Colomé Font"
  bio: "Music-Tech Generalist with over a decade of experience across the music industry"
  location: "Terrassa, Barcelona"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/oriolcolomefont"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/ocf"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Feed settings
feed:
  posts_limit: 20
  excerpt_only: false

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/
  notebooks:
    output: true
    permalink: /notebooks/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Oriol Colomé Font"
      comments: true
      share: true
  - scope:
      path: ""
      type: "notebooks"
    values:
      layout: "notebook"
      author: "Oriol Colomé Font"

# Blog settings
blog:
  title: "Music Tech Insights"
  description: "Thoughts on music technology, MIR, and industry trends"
  posts_per_page: 5
  categories:
    - "Music Information Retrieval"
    - "Audio Processing"
    - "Industry Insights"
    - "Project Management"
    - "Deep Learning"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - README.md
  - DEPLOYMENT_READY.md
  - scripts/
  - "*.plan.md"

# Include files
include:
  - _pages
  - _posts
  - assets
  - robots.txt

# Performance optimizations
sass:
  style: compressed

# Liquid rendering
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: false
